


const data = [
    {
        id: 1,
        name: "Project 1",
        info: "Project 1 ritatis! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias corrupti, ex ad pariatur perspiciatis eaque neque praesentium maiores est rem consequatur quo dolor id quidem dolore possimus explicabo quas Venia Porro voluptate vitae id aliquid aut dolorem, corrupti, sapiente provident nesciunt neque impedit.Eveniet eius fugit earum architecto, enim impedit nostrum ut consectetur.Veniam iure ad vitae ullam natus provident.     Dignissimos cupiditate autem explicabo quas magnam ex id blanditiis veniam nisi alias quam ut impedit possimus nulla neque, asperiores, veritatis beatae.Fuga possimus ratione repudiandae praesentium! Corrupti laudantium pariatur aut.     Dolorum sequi eligendi modi voluptatem! Sequi eligendi ipsa necessitatibus libero, consectetur quaerat vitae itaque est, consequuntur error fugiat voluptates accusantium similique iure dolorum quos laboriosam, et reiciendis! Enim, officia.Velit!        Quos illum earum exercitationem itaque magnam eius velit nostrum? Laudantium tempora atque incidunt id.Quos suscipit explicabo quis earum, ea consectetur sed quaerat repudiandae! Nesciunt reiciendis adipisci eum aut nam.        Voluptate doloribus beatae nihil voluptatibus voluptas.Obcaecati aspernatur commodi ducimus aut, hic deleniti quidem voluptas ab dolor quia explicabo quaerat perspiciatis enim nemo in sunt? Reprehenderit unde sequi quas animi.  Atque facilis unde tempore ratione nemo tempora a, illo aut laudantium non quam quisquam! Aut officiis a maxime, unde sapiente veniam molestias asperiores nulla facilis sed mollitia fugiat ut laboriosam?        Explicabo adipisci quibusdam incidunt dignissimos nemo totam minima architecto corporis voluptate? Explicabo beatae voluptas dicta et, id voluptates qui consectetur corporis culpa nesciunt deserunt hic? Quam hic unde soluta nulla",
        image:"https://cdn.thecodehelp.in/Agra.jpeg",
        price:"35,222",
    },
    {
        id: 2,
        name: "Project 2",
        info: "Project 2 ritatis! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias corrupti, ex ad pariatur perspiciatis eaque neque praesentium maiores est rem consequatur quo dolor id quidem dolore possimus explicabo quas Venia Porro voluptate vitae id aliquid aut dolorem, corrupti, sapiente provident nesciunt neque impedit.Eveniet eius fugit earum architecto, enim impedit nostrum ut consectetur.Veniam iure ad vitae ullam natus provident.     Dignissimos cupiditate autem explicabo quas magnam ex id blanditiis veniam nisi alias quam ut impedit possimus nulla neque, asperiores, veritatis beatae.Fuga possimus ratione repudiandae praesentium! Corrupti laudantium pariatur aut.     Dolorum sequi eligendi modi voluptatem! Sequi eligendi ipsa necessitatibus libero, consectetur quaerat vitae itaque est, consequuntur error fugiat voluptates accusantium similique iure dolorum quos laboriosam, et reiciendis! Enim, officia.Velit!        Quos illum earum exercitationem itaque magnam eius velit nostrum? Laudantium tempora atque incidunt id.Quos suscipit explicabo quis earum, ea consectetur sed quaerat repudiandae! Nesciunt reiciendis adipisci eum aut nam.        Voluptate doloribus beatae nihil voluptatibus voluptas.Obcaecati aspernatur commodi ducimus aut, hic deleniti quidem voluptas ab dolor quia explicabo quaerat perspiciatis enim nemo in sunt? Reprehenderit unde sequi quas animi.  Atque facilis unde tempore ratione nemo tempora a, illo aut laudantium non quam quisquam! Aut officiis a maxime, unde sapiente veniam molestias asperiores nulla facilis sed mollitia fugiat ut laboriosam?        Explicabo adipisci quibusdam incidunt dignissimos nemo totam minima architecto corporis voluptate? Explicabo beatae voluptas dicta et, id voluptates qui consectetur corporis culpa nesciunt deserunt hic? Quam hic unde soluta nulla",
        image:"https://cdn.thecodehelp.in/Agra.jpeg",
        price:"35,222",
    },
    {
        id: 3,
        name: "Project 3",
        info: "Project 3 ritatis! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias corrupti, ex ad pariatur perspiciatis eaque neque praesentium maiores est rem consequatur quo dolor id quidem dolore possimus explicabo quas Venia Porro voluptate vitae id aliquid aut dolorem, corrupti, sapiente provident nesciunt neque impedit.Eveniet eius fugit earum architecto, enim impedit nostrum ut consectetur.Veniam iure ad vitae ullam natus provident.     Dignissimos cupiditate autem explicabo quas magnam ex id blanditiis veniam nisi alias quam ut impedit possimus nulla neque, asperiores, veritatis beatae.Fuga possimus ratione repudiandae praesentium! Corrupti laudantium pariatur aut.     Dolorum sequi eligendi modi voluptatem! Sequi eligendi ipsa necessitatibus libero, consectetur quaerat vitae itaque est, consequuntur error fugiat voluptates accusantium similique iure dolorum quos laboriosam, et reiciendis! Enim, officia.Velit!        Quos illum earum exercitationem itaque magnam eius velit nostrum? Laudantium tempora atque incidunt id.Quos suscipit explicabo quis earum, ea consectetur sed quaerat repudiandae! Nesciunt reiciendis adipisci eum aut nam.        Voluptate doloribus beatae nihil voluptatibus voluptas.Obcaecati aspernatur commodi ducimus aut, hic deleniti quidem voluptas ab dolor quia explicabo quaerat perspiciatis enim nemo in sunt? Reprehenderit unde sequi quas animi.  Atque facilis unde tempore ratione nemo tempora a, illo aut laudantium non quam quisquam! Aut officiis a maxime, unde sapiente veniam molestias asperiores nulla facilis sed mollitia fugiat ut laboriosam?        Explicabo adipisci quibusdam incidunt dignissimos nemo totam minima architecto corporis voluptate? Explicabo beatae voluptas dicta et, id voluptates qui consectetur corporis culpa nesciunt deserunt hic? Quam hic unde soluta nulla",
        image:"https://cdn.thecodehelp.in/Agra.jpeg",
        price:"35,222",
    },
    {
        id: 4,
        name: "Project 4",
        info: "Project 4 ritatis! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias corrupti, ex ad pariatur perspiciatis eaque neque praesentium maiores est rem consequatur quo dolor id quidem dolore possimus explicabo quas Venia Porro voluptate vitae id aliquid aut dolorem, corrupti, sapiente provident nesciunt neque impedit.Eveniet eius fugit earum architecto, enim impedit nostrum ut consectetur.Veniam iure ad vitae ullam natus provident.     Dignissimos cupiditate autem explicabo quas magnam ex id blanditiis veniam nisi alias quam ut impedit possimus nulla neque, asperiores, veritatis beatae.Fuga possimus ratione repudiandae praesentium! Corrupti laudantium pariatur aut.     Dolorum sequi eligendi modi voluptatem! Sequi eligendi ipsa necessitatibus libero, consectetur quaerat vitae itaque est, consequuntur error fugiat voluptates accusantium similique iure dolorum quos laboriosam, et reiciendis! Enim, officia.Velit!        Quos illum earum exercitationem itaque magnam eius velit nostrum? Laudantium tempora atque incidunt id.Quos suscipit explicabo quis earum, ea consectetur sed quaerat repudiandae! Nesciunt reiciendis adipisci eum aut nam.        Voluptate doloribus beatae nihil voluptatibus voluptas.Obcaecati aspernatur commodi ducimus aut, hic deleniti quidem voluptas ab dolor quia explicabo quaerat perspiciatis enim nemo in sunt? Reprehenderit unde sequi quas animi.  Atque facilis unde tempore ratione nemo tempora a, illo aut laudantium non quam quisquam! Aut officiis a maxime, unde sapiente veniam molestias asperiores nulla facilis sed mollitia fugiat ut laboriosam?        Explicabo adipisci quibusdam incidunt dignissimos nemo totam minima architecto corporis voluptate? Explicabo beatae voluptas dicta et, id voluptates qui consectetur corporis culpa nesciunt deserunt hic? Quam hic unde soluta nulla",
        image:"https://cdn.thecodehelp.in/Agra.jpeg",
        price:"35,222",
    }
    , {
        id: 5,
        name: "Project 5",
        info: "Project 5 ritatis! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias corrupti, ex ad pariatur perspiciatis eaque neque praesentium maiores est rem consequatur quo dolor id quidem dolore possimus explicabo quas Venia Porro voluptate vitae id aliquid aut dolorem, corrupti, sapiente provident nesciunt neque impedit.Eveniet eius fugit earum architecto, enim impedit nostrum ut consectetur.Veniam iure ad vitae ullam natus provident.     Dignissimos cupiditate autem explicabo quas magnam ex id blanditiis veniam nisi alias quam ut impedit possimus nulla neque, asperiores, veritatis beatae.Fuga possimus ratione repudiandae praesentium! Corrupti laudantium pariatur aut.     Dolorum sequi eligendi modi voluptatem! Sequi eligendi ipsa necessitatibus libero, consectetur quaerat vitae itaque est, consequuntur error fugiat voluptates accusantium similique iure dolorum quos laboriosam, et reiciendis! Enim, officia.Velit!        Quos illum earum exercitationem itaque magnam eius velit nostrum? Laudantium tempora atque incidunt id.Quos suscipit explicabo quis earum, ea consectetur sed quaerat repudiandae! Nesciunt reiciendis adipisci eum aut nam.        Voluptate doloribus beatae nihil voluptatibus voluptas.Obcaecati aspernatur commodi ducimus aut, hic deleniti quidem voluptas ab dolor quia explicabo quaerat perspiciatis enim nemo in sunt? Reprehenderit unde sequi quas animi.  Atque facilis unde tempore ratione nemo tempora a, illo aut laudantium non quam quisquam! Aut officiis a maxime, unde sapiente veniam molestias asperiores nulla facilis sed mollitia fugiat ut laboriosam?        Explicabo adipisci quibusdam incidunt dignissimos nemo totam minima architecto corporis voluptate? Explicabo beatae voluptas dicta et, id voluptates qui consectetur corporis culpa nesciunt deserunt hic? Quam hic unde soluta nulla",
        image:"https://cdn.thecodehelp.in/Agra.jpeg",
        price:"35,222",
    }
    , {
        id: 6,
        name: "Project 6",
        info: "Project 6 ritatis! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias corrupti, ex ad pariatur perspiciatis eaque neque praesentium maiores est rem consequatur quo dolor id quidem dolore possimus explicabo quas Venia Porro voluptate vitae id aliquid aut dolorem, corrupti, sapiente provident nesciunt neque impedit.Eveniet eius fugit earum architecto, enim impedit nostrum ut consectetur.Veniam iure ad vitae ullam natus provident.     Dignissimos cupiditate autem explicabo quas magnam ex id blanditiis veniam nisi alias quam ut impedit possimus nulla neque, asperiores, veritatis beatae.Fuga possimus ratione repudiandae praesentium! Corrupti laudantium pariatur aut.     Dolorum sequi eligendi modi voluptatem! Sequi eligendi ipsa necessitatibus libero, consectetur quaerat vitae itaque est, consequuntur error fugiat voluptates accusantium similique iure dolorum quos laboriosam, et reiciendis! Enim, officia.Velit!        Quos illum earum exercitationem itaque magnam eius velit nostrum? Laudantium tempora atque incidunt id.Quos suscipit explicabo quis earum, ea consectetur sed quaerat repudiandae! Nesciunt reiciendis adipisci eum aut nam.        Voluptate doloribus beatae nihil voluptatibus voluptas.Obcaecati aspernatur commodi ducimus aut, hic deleniti quidem voluptas ab dolor quia explicabo quaerat perspiciatis enim nemo in sunt? Reprehenderit unde sequi quas animi.  Atque facilis unde tempore ratione nemo tempora a, illo aut laudantium non quam quisquam! Aut officiis a maxime, unde sapiente veniam molestias asperiores nulla facilis sed mollitia fugiat ut laboriosam?        Explicabo adipisci quibusdam incidunt dignissimos nemo totam minima architecto corporis voluptate? Explicabo beatae voluptas dicta et, id voluptates qui consectetur corporis culpa nesciunt deserunt hic? Quam hic unde soluta nulla",
        image:"https://cdn.thecodehelp.in/Agra.jpeg",
        price:"35,222",
    },
    {
        id: 7,
        name: "Project 7",
        info: "Project 7 ritatis! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias corrupti, ex ad pariatur perspiciatis eaque neque praesentium maiores est rem consequatur quo dolor id quidem dolore possimus explicabo quas Venia Porro voluptate vitae id aliquid aut dolorem, corrupti, sapiente provident nesciunt neque impedit.Eveniet eius fugit earum architecto, enim impedit nostrum ut consectetur.Veniam iure ad vitae ullam natus provident.     Dignissimos cupiditate autem explicabo quas magnam ex id blanditiis veniam nisi alias quam ut impedit possimus nulla neque, asperiores, veritatis beatae.Fuga possimus ratione repudiandae praesentium! Corrupti laudantium pariatur aut.     Dolorum sequi eligendi modi voluptatem! Sequi eligendi ipsa necessitatibus libero, consectetur quaerat vitae itaque est, consequuntur error fugiat voluptates accusantium similique iure dolorum quos laboriosam, et reiciendis! Enim, officia.Velit!        Quos illum earum exercitationem itaque magnam eius velit nostrum? Laudantium tempora atque incidunt id.Quos suscipit explicabo quis earum, ea consectetur sed quaerat repudiandae! Nesciunt reiciendis adipisci eum aut nam.        Voluptate doloribus beatae nihil voluptatibus voluptas.Obcaecati aspernatur commodi ducimus aut, hic deleniti quidem voluptas ab dolor quia explicabo quaerat perspiciatis enim nemo in sunt? Reprehenderit unde sequi quas animi.  Atque facilis unde tempore ratione nemo tempora a, illo aut laudantium non quam quisquam! Aut officiis a maxime, unde sapiente veniam molestias asperiores nulla facilis sed mollitia fugiat ut laboriosam?        Explicabo adipisci quibusdam incidunt dignissimos nemo totam minima architecto corporis voluptate? Explicabo beatae voluptas dicta et, id voluptates qui consectetur corporis culpa nesciunt deserunt hic? Quam hic unde soluta nulla",
        image:"https://cdn.thecodehelp.in/Agra.jpeg",
        price:"35,222",
    },
    {
        id: 8,
        name: "Project 8",
        info: "Project 8 ritatis! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias corrupti, ex ad pariatur perspiciatis eaque neque praesentium maiores est rem consequatur quo dolor id quidem dolore possimus explicabo quas Venia Porro voluptate vitae id aliquid aut dolorem, corrupti, sapiente provident nesciunt neque impedit.Eveniet eius fugit earum architecto, enim impedit nostrum ut consectetur.Veniam iure ad vitae ullam natus provident.     Dignissimos cupiditate autem explicabo quas magnam ex id blanditiis veniam nisi alias quam ut impedit possimus nulla neque, asperiores, veritatis beatae.Fuga possimus ratione repudiandae praesentium! Corrupti laudantium pariatur aut.     Dolorum sequi eligendi modi voluptatem! Sequi eligendi ipsa necessitatibus libero, consectetur quaerat vitae itaque est, consequuntur error fugiat voluptates accusantium similique iure dolorum quos laboriosam, et reiciendis! Enim, officia.Velit!        Quos illum earum exercitationem itaque magnam eius velit nostrum? Laudantium tempora atque incidunt id.Quos suscipit explicabo quis earum, ea consectetur sed quaerat repudiandae! Nesciunt reiciendis adipisci eum aut nam.        Voluptate doloribus beatae nihil voluptatibus voluptas.Obcaecati aspernatur commodi ducimus aut, hic deleniti quidem voluptas ab dolor quia explicabo quaerat perspiciatis enim nemo in sunt? Reprehenderit unde sequi quas animi.  Atque facilis unde tempore ratione nemo tempora a, illo aut laudantium non quam quisquam! Aut officiis a maxime, unde sapiente veniam molestias asperiores nulla facilis sed mollitia fugiat ut laboriosam?        Explicabo adipisci quibusdam incidunt dignissimos nemo totam minima architecto corporis voluptate? Explicabo beatae voluptas dicta et, id voluptates qui consectetur corporis culpa nesciunt deserunt hic? Quam hic unde soluta nulla",
        image:"https://cdn.thecodehelp.in/Agra.jpeg",
        price:"35,222",
    },
]
export default data;